blank_issues_enabled: true
contact_links:
  - name: Discord（一般問題／建議 / General questions & suggestions）
    url: https://discord.gg/Gur2V67
    about: 操作詢問或功能建議可以到 Discord。For usage questions or feature suggestions, join the Discord.
