# -*- coding: utf-8 -*-
"""由 scripts/blender/modcars.json 產生 Steam 討論串稿源 STEAM_DISCUSSION_modcars.md／_EN.md（支援的 MOD 車與申請）。

用法（repo 根目錄）：
    python scripts/gen_modcar_list.py           # 重寫兩個稿源；同一份 modcars.json 重跑結果一致
    python scripts/gen_modcar_list.py --check   # 只比對，稿源過期就失敗

modcars.json 也是 DockSpots.lua MOD 區塊的來源（scripts/blender/dock_spots.py）；這裡順便核對兩邊一致，
清單上的車在位置表裡都要有一列，免得清單寫了支援、遊戲裡卻退回公式。
貼回 Steam 前去掉檔頭 <!-- --> 註解（家族 release.md）。BBCode 的 `[`：名稱裡的方括號換成圓括號，
免得同一行的 `[ … ]` 被 Steam 當成無效標籤、連帶吃掉 [b]。
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "scripts", "blender", "modcars.json")
DOCK = os.path.join(REPO, "MOD", "MinidoracatKnoxPassFor42", "Contents", "mods", "MinidoracatKnoxPassFor42", "42",
                    "media", "lua", "shared", "MinidoracatKnoxPass", "DockSpots.lua")
ISSUE = "https://github.com/Minidoracat/MinidoracatKnoxPassFor42/issues/new?template=modcar-request.yml"
DISCORD = "https://discord.gg/Gur2V67"
WORKSHOP = "https://steamcommunity.com/sharedfiles/filedetails/?id="

TEXT = {
    "CH": {
        "file": "STEAM_DISCUSSION_modcars.md",
        "head": [
            "<!-- 由 scripts/gen_modcar_list.py 從 scripts/blender/modcars.json 產生，不要手改；改清單請改 modcars.json 再重跑 -->",
            "<!-- Steam 討論區貼文稿源（繁中）：有擋風玻璃位置表的 MOD 車與申請方式；完整說明串的感應盒段落連到這裡 -->",
            "<!-- 討論串網址：（待建立，首發後補進 STEAM_DISCUSSION_guide*.md） -->",
            "<!-- 標題：🚗 支援的 MOD 車與申請 -->",
        ],
        "other": "[b]English version:[/b] [url={KP_MODCARS_EN}]🚗 Supported Modded Vehicles & Requests[/url]",
        "intro": "車上裝了感應盒，擋風玻璃上緣看得到固定座和盒子。原版車全部支援；MOD 車要先知道它的擋風玻璃在哪裡，所以只有下面這些車對好了位置。",
        "missing_h": "❓ 表上沒有的車會怎樣",
        "missing": [
            "[b]功能完全照常[/b]：每台有電瓶的車都能裝感應盒，登記、開門、充電都一樣。",
            "[b]只是未必看得到[/b]：盒子的位置改用車輛大小推算，常落在擋風玻璃裡面，被玻璃擋住。",
        ],
        "list_h": "✅ 已支援的 MOD 車（{n} 個 MOD）",
        "legend": "位置是從車輛模型算出來的，用遊戲視角（由上往下斜看）避開車輛生成時可能帶的配件（車頂燈架、行李架、遮陽板等），每台都看過預覽圖；標 ✔ 的也在遊戲裡實際看過。其他 MOD 沿用這些車身的車（例如同系列的擴充包）也一樣支援。車上加裝的配件可能擋住盒子，例如自己裝的擋風玻璃裝甲。",
        "addons": "（含同一個 Workshop 項目的 {ids}）",
        "sep": "、",
        "colon": "：",
        "ask_h": "📮 申請新車",
        "ask_pre": "車要是 Build 42 的 MOD，而且有電瓶（拖車、腳踏車本來就不裝感應盒）。任選一種方式：",
        "ask": [
            "[b]在這串回覆[/b]：貼上車輛 MOD 的 Workshop 連結和車名。",
            "[b]GitHub Issue[/b]：用「MOD 車位置申請」表單 " + ISSUE,
            "[b]Discord[/b]：" + DISCORD,
        ],
        "ask_post": "附一張裝上感應盒後從車頭前方拍的截圖更好。MOD 車更新換了車身、盒子跑到怪地方，也用同樣的方式回報。",
        "cant_h": "哪些車做不到",
        "cant": [
            "擋風玻璃不在車頭正中間（例如裝甲車偏一側的觀察窗）：盒子只能放在中線，會落在車殼上。",
        ],
        "blocked": "同車身但遊戲裡看不到盒子（功能照常）",
        "why": {"ladder": "雲梯架在駕駛室上方，擋住擋風玻璃", "armor": "出廠就裝了擋風玻璃裝甲"},
        "item": "{name}（{why}）",
    },
    "EN": {
        "file": "STEAM_DISCUSSION_modcars_EN.md",
        "head": [
            "<!-- Generated by scripts/gen_modcar_list.py from scripts/blender/modcars.json; do not edit by hand, edit modcars.json and rerun -->",
            "<!-- Steam discussion post source (English): modded vehicles with a windshield position table, and how to request one -->",
            "<!-- Thread URL: (to be created after the first upload; then link it from STEAM_DISCUSSION_guide*.md) -->",
            "<!-- Title: 🚗 Supported Modded Vehicles & Requests -->",
        ],
        "other": "[b]中文版：[/b] [url={KP_MODCARS_CH}]🚗 支援的 MOD 車與申請[/url]",
        "intro": "With a tag installed, the mount and the tag show up at the top of the windshield. Every vanilla vehicle is supported; for modded vehicles we first need to know where the windshield is, so only the vehicles below have a matched position.",
        "missing_h": "❓ What about vehicles not on the list",
        "missing": [
            "[b]Everything still works[/b]: every vehicle with a battery takes a tag, and registering, opening gates and charging work the same.",
            "[b]You may just not see it[/b]: the position is estimated from the vehicle size and often ends up behind the windshield, hidden by the glass.",
        ],
        "list_h": "✅ Supported modded vehicles ({n} mods)",
        "legend": "Positions are computed from the vehicle models, using the game's top-down camera angle to stay clear of accessories a vehicle can spawn with (roof light bars, roof racks, sun visors and so on), and every one was checked in a preview render; vehicles marked ✔ were also checked in game. Vehicles from other mods that reuse these bodies (such as expansion packs of the same series) are covered too. Accessories added to a vehicle can hide the tag, for example windshield armor you install yourself.",
        "addons": " (including {ids} from the same Workshop item)",
        "sep": ", ",
        "colon": ": ",
        "ask_h": "📮 Request a vehicle",
        "ask_pre": "The vehicle must be a Build 42 mod with a battery (trailers and bicycles never take a tag). Any of these works:",
        "ask": [
            "[b]Reply in this thread[/b] with the vehicle mod's Workshop link and the vehicle name.",
            "[b]GitHub Issue[/b]: use the \"Modded vehicle position request\" form " + ISSUE,
            "[b]Discord[/b]: " + DISCORD,
        ],
        "ask_post": "A screenshot from in front of the vehicle with the tag installed helps. If a mod update changes the body and the tag ends up in an odd place, report it the same way.",
        "cant_h": "What cannot be supported",
        "cant": [
            "Windshields that are not centred on the vehicle (such as an armoured vehicle's offset vision slit): the tag can only sit on the centre line and would end up on the body.",
        ],
        "blocked": "Same body, but the tag can't be seen in game (everything still works)",
        "why": {"ladder": "the ladder sits over the cab and hides the windshield", "armor": "comes with windshield armor fitted"},
        "item": "{name} ({why})",
    },
}


def plain(s):
    return s.replace("[", "(").replace("]", ")")


def sort_key(mod):
    return re.sub(r"^'\d+\s*", "", mod["name"]).lower()   # KI5 名稱開頭是年份，照廠牌車名排


def render(mods, t):
    out = t["head"] + ["", t["other"], "", t["intro"], "", "[h2]" + t["missing_h"] + "[/h2]", "[list]"]
    out += ["[*] " + s for s in t["missing"]] + ["[/list]", ""]
    out += ["[h2]" + t["list_h"].format(n=len(mods)) + "[/h2]", t["legend"], "[list]"]
    for mod in sorted(mods, key=sort_key):
        names = {}
        for car in mod["models"]:
            for n in car["vehicles"].values():
                names[n] = names.get(n) or car["status"] == "ingame"
        cars = t["sep"].join(plain(n) + (" ✔" if names[n] else "") for n in sorted(names))
        line = "[*] [b][url=%s%s]%s[/url][/b]" % (WORKSHOP, mod["workshop"], plain(mod["name"]))
        if mod.get("addons"):
            line += t["addons"].format(ids=t["sep"].join(mod["addons"]))
        out.append(line + t["colon"] + cars)
    out += ["[/list]", "", "[h2]" + t["ask_h"] + "[/h2]", t["ask_pre"], "[olist]"]
    out += ["[*] " + s for s in t["ask"]] + ["[/olist]", t["ask_post"], ""]
    blocked = [t["item"].format(name=plain(u["name"]), why=t["why"][u["why"]]) for mod in sorted(mods, key=sort_key)
               for car in mod["models"] for u in car.get("unsupported", {}).values()]
    out += ["[h3]" + t["cant_h"] + "[/h3]", "[list]"] + ["[*] " + s for s in t["cant"]]
    if blocked:
        out.append("[*] " + t["blocked"] + t["colon"] + t["sep"].join(blocked))
    out.append("[/list]")
    return "\n".join(out) + "\n"


def main():
    mods = json.load(open(MANIFEST, encoding="utf-8"))["mods"]
    # DockSpots.lua MOD 區塊每列註解列出用這個 mesh 的「modId file」，以「; 」分隔
    rows = {u for line in re.findall(r'^    \["[^"]+"\] = \{[^}]*\},\s+-- (.+)$', open(DOCK, encoding="utf-8").read(), re.M)
            for u in line.split("; ")}
    missing = ["%s %s" % (m["modId"], c["file"]) for m in mods for c in m["models"]
               if "%s %s" % (m["modId"], c["file"]) not in rows]
    if missing:
        raise SystemExit("modcars.json models without a DockSpots.lua row (rerun scripts/blender/dock_spots.py): %s" % missing)
    check = "--check" in sys.argv
    stale = []
    for t in TEXT.values():
        path = os.path.join(REPO, t["file"])
        text = render(mods, t)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            stale.append(t["file"])
            if not check:
                open(path, "w", encoding="utf-8", newline="\n").write(text)
    if check and stale:
        raise SystemExit("stale: %s (run python scripts/gen_modcar_list.py)" % stale)
    print("OK" if not stale else "wrote %s" % stale)


if __name__ == "__main__":
    main()
